### ISSUE TITLE
21 Errors

### ISSUE THREAD

**Issue by goharlatif63790** [nakky/CaCom#1]
The project has got 21 errors -_-

**Comment by nakky** [comment]
I've committed fixed code.

**Comment by goharlatif63790** [comment]
Hey, Thanks for that, When i connect the reader it does not enables the program to let me read. Is this happening with you as well?

**Comment by nakky** [comment]
I can read data with a NFC reader which conforms to Windows PC/SC API. I use NFC tags which include NTAG213 chipset. There are many types of NFC tags and they has each memory layout and updating rules, so you have to set right values for the tag to "UserMemoryAddress" and "UpdateSize". (For NTAG 213, UserMemoryAddress=4 and UpdateSize=4.)
Also, "NFCReaderWriter" app can read/write NDEF message only. If UserMemory in your tag do not include NDEF message, nothing is read.

**Comment by goharlatif63790** [comment]
The one that I have downloaded from here is not working on reading the card :/

**Comment by goharlatif63790** [comment]
![Capture](https://user-images.githubusercontent.com/26367792/72333111-308fd580-36b3-11ea-9b61-22c93618ea51.JPG)

**Comment by goharlatif63790** [comment]
nothing Is enabled here so I am confused.

**Comment by nakky** [comment]
Read and Write buttons should be enabled when you bring the card closer to the NFC device. 
It looks like you are using USB Card Reader from the log, and the reader conforms to Windows PC/SC API. There seems to be no problem.
Can you tell me which card you use?
